M48
; DRILL file {KiCad 9.0.6-1.fc43} date 2026-03-20T21:24:41+0000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-20T21:24:41+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-1.fc43
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1122
%
G90
G05
T1
X7.2807Y-3.8943
X7.2807Y-4.2085
T2
X3.6402Y-2.3591
X3.6402Y-5.8591
M30
